apiVersion: charts.nginx.org/v1alpha1
kind: NginxIngress
metadata:
  name: nginxingress-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nginx-ingress/values.yaml
  controller:
    defaultTLS:
      secret: ""
    enableCustomResources: true
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 3.1.1-ubi
    ingressClass: nginx
    kind: deployment
    nginxplus: true
    service:
      type: NodePort
  rbac:
    create: true
